<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HotChocolate.AspNetCore" Version="14.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\orders.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
