apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-config
  namespace: default
data:
  users-service-url: "http://users-service:5001"
  orders-service-url: "http://orders-service:5002"
  payments-service-url: "http://payments-service:5003"
